config:
  (): colpali_engine.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path trained_models/Vintern1B_3_5_test_colpali_puretext_refine
  processor:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColInternVL2Processor
    pretrained_model_name_or_path: "/data/llm/colpali/Vintern1B_3_5_test_colpali_puretext_merged_good-19999vocab" #"5CD-AI/Vintern-1B-v3_5" # "./models/paligemma-3b-mix-448"
    # num_image_tokens: 2048
    # max_length: 100

  model:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColInternVL2
    pretrained_model_name_or_path: "/data/llm/colpali/Vintern1B_3_5_test_colpali_puretext_merged_good-19999vocab" # "/data/llm/colpali/scripts/configs/colinternvl2/trained_models/Vintern1B_3_5_test_colpali_puretext_merged_good"
    torch_dtype:  !ext torch.bfloat16
    attn_implementation: "flash_attention_2"
    # quantization_config:
    #     (): transformers.BitsAndBytesConfig
    #     load_in_4bit: true
    #     bnb_4bit_quant_type: "nf4"
    #     bnb_4bit_compute_dtype:  "bfloat16"
    #     bnb_4bit_use_double_quant: true

  dataset_loading_func: !ext colpali_engine.utils.dataset_transformation.load_train_set
  eval_dataset_loader: !import ../data/test_data.yaml

  max_length: 1100
  run_eval: true
  add_suffix: true
  loss_func:
    (): colpali_engine.loss.late_interaction_losses.ColbertPairwiseCELoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 1.0
    per_device_train_batch_size: 16
    gradient_accumulation_steps: 4
    per_device_eval_batch_size: 4
    eval_strategy: "steps"
    dataloader_num_workers: 8
    bf16: true
    save_steps: 100
    logging_steps: 10
    eval_steps: 1000000000
    warmup_steps: 100
    learning_rate: 0.00005
    save_total_limit: 1
    # gradient_checkpointing: true
    # gradient_checkpointing_kwargs: { "use_reentrant": false }
    # resume_from_checkpoint: true
    # deepspeed: "zero_stage3_config.json"
    # optim: "paged_adamw_8bit"

  peft_config:
    (): peft.LoraConfig
    r: 8
    lora_alpha: 16
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: '(.*(model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj|embed_tokens).*$|.*(custom_text_proj).*$)'
    # target_modules: '(.*(model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'
    # modules_to_save: 'custom_text_proj'
    # target_modules: '(.*(language_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'

